name: Regular base image update check
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: gitpod/openvscode-server
          image: stevenross/openvscode-server-static-token-bypass

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: stevenross/openvscode-server-static-token-bypass:latest
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
